// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	render "lets-go-tetris/render"
	sync "sync"

	sdl "github.com/veandco/go-sdl2/sdl"
)

type Window struct {
	DestroyStub        func() error
	destroyMutex       sync.RWMutex
	destroyArgsForCall []struct {
	}
	destroyReturns struct {
		result1 error
	}
	destroyReturnsOnCall map[int]struct {
		result1 error
	}
	GetSurfaceStub        func() (*sdl.Surface, error)
	getSurfaceMutex       sync.RWMutex
	getSurfaceArgsForCall []struct {
	}
	getSurfaceReturns struct {
		result1 *sdl.Surface
		result2 error
	}
	getSurfaceReturnsOnCall map[int]struct {
		result1 *sdl.Surface
		result2 error
	}
	UpdateSurfaceStub        func() error
	updateSurfaceMutex       sync.RWMutex
	updateSurfaceArgsForCall []struct {
	}
	updateSurfaceReturns struct {
		result1 error
	}
	updateSurfaceReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Window) Destroy() error {
	fake.destroyMutex.Lock()
	ret, specificReturn := fake.destroyReturnsOnCall[len(fake.destroyArgsForCall)]
	fake.destroyArgsForCall = append(fake.destroyArgsForCall, struct {
	}{})
	fake.recordInvocation("Destroy", []interface{}{})
	fake.destroyMutex.Unlock()
	if fake.DestroyStub != nil {
		return fake.DestroyStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.destroyReturns
	return fakeReturns.result1
}

func (fake *Window) DestroyCallCount() int {
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	return len(fake.destroyArgsForCall)
}

func (fake *Window) DestroyCalls(stub func() error) {
	fake.destroyMutex.Lock()
	defer fake.destroyMutex.Unlock()
	fake.DestroyStub = stub
}

func (fake *Window) DestroyReturns(result1 error) {
	fake.destroyMutex.Lock()
	defer fake.destroyMutex.Unlock()
	fake.DestroyStub = nil
	fake.destroyReturns = struct {
		result1 error
	}{result1}
}

func (fake *Window) DestroyReturnsOnCall(i int, result1 error) {
	fake.destroyMutex.Lock()
	defer fake.destroyMutex.Unlock()
	fake.DestroyStub = nil
	if fake.destroyReturnsOnCall == nil {
		fake.destroyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.destroyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Window) GetSurface() (*sdl.Surface, error) {
	fake.getSurfaceMutex.Lock()
	ret, specificReturn := fake.getSurfaceReturnsOnCall[len(fake.getSurfaceArgsForCall)]
	fake.getSurfaceArgsForCall = append(fake.getSurfaceArgsForCall, struct {
	}{})
	fake.recordInvocation("GetSurface", []interface{}{})
	fake.getSurfaceMutex.Unlock()
	if fake.GetSurfaceStub != nil {
		return fake.GetSurfaceStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getSurfaceReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Window) GetSurfaceCallCount() int {
	fake.getSurfaceMutex.RLock()
	defer fake.getSurfaceMutex.RUnlock()
	return len(fake.getSurfaceArgsForCall)
}

func (fake *Window) GetSurfaceCalls(stub func() (*sdl.Surface, error)) {
	fake.getSurfaceMutex.Lock()
	defer fake.getSurfaceMutex.Unlock()
	fake.GetSurfaceStub = stub
}

func (fake *Window) GetSurfaceReturns(result1 *sdl.Surface, result2 error) {
	fake.getSurfaceMutex.Lock()
	defer fake.getSurfaceMutex.Unlock()
	fake.GetSurfaceStub = nil
	fake.getSurfaceReturns = struct {
		result1 *sdl.Surface
		result2 error
	}{result1, result2}
}

func (fake *Window) GetSurfaceReturnsOnCall(i int, result1 *sdl.Surface, result2 error) {
	fake.getSurfaceMutex.Lock()
	defer fake.getSurfaceMutex.Unlock()
	fake.GetSurfaceStub = nil
	if fake.getSurfaceReturnsOnCall == nil {
		fake.getSurfaceReturnsOnCall = make(map[int]struct {
			result1 *sdl.Surface
			result2 error
		})
	}
	fake.getSurfaceReturnsOnCall[i] = struct {
		result1 *sdl.Surface
		result2 error
	}{result1, result2}
}

func (fake *Window) UpdateSurface() error {
	fake.updateSurfaceMutex.Lock()
	ret, specificReturn := fake.updateSurfaceReturnsOnCall[len(fake.updateSurfaceArgsForCall)]
	fake.updateSurfaceArgsForCall = append(fake.updateSurfaceArgsForCall, struct {
	}{})
	fake.recordInvocation("UpdateSurface", []interface{}{})
	fake.updateSurfaceMutex.Unlock()
	if fake.UpdateSurfaceStub != nil {
		return fake.UpdateSurfaceStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.updateSurfaceReturns
	return fakeReturns.result1
}

func (fake *Window) UpdateSurfaceCallCount() int {
	fake.updateSurfaceMutex.RLock()
	defer fake.updateSurfaceMutex.RUnlock()
	return len(fake.updateSurfaceArgsForCall)
}

func (fake *Window) UpdateSurfaceCalls(stub func() error) {
	fake.updateSurfaceMutex.Lock()
	defer fake.updateSurfaceMutex.Unlock()
	fake.UpdateSurfaceStub = stub
}

func (fake *Window) UpdateSurfaceReturns(result1 error) {
	fake.updateSurfaceMutex.Lock()
	defer fake.updateSurfaceMutex.Unlock()
	fake.UpdateSurfaceStub = nil
	fake.updateSurfaceReturns = struct {
		result1 error
	}{result1}
}

func (fake *Window) UpdateSurfaceReturnsOnCall(i int, result1 error) {
	fake.updateSurfaceMutex.Lock()
	defer fake.updateSurfaceMutex.Unlock()
	fake.UpdateSurfaceStub = nil
	if fake.updateSurfaceReturnsOnCall == nil {
		fake.updateSurfaceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateSurfaceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Window) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	fake.getSurfaceMutex.RLock()
	defer fake.getSurfaceMutex.RUnlock()
	fake.updateSurfaceMutex.RLock()
	defer fake.updateSurfaceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Window) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ render.Window = new(Window)
